spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rymcu_subject?autoReconnect=true&useSSL=false
    username: rymcu_subject
    password: 1234
mybatis:
  typeAliasesPackage: com.rymcu.subject.domain
  mapperLocations: classpath:mapperxml/*.xml
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
