package com.rymcu.subject.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * @author 🐛
 * @TableName subject_sign_err
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AddSignErrDTO implements Serializable {
    /**
     * 主键编号
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private Long id;

    /**
     * 题目编号
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private Long sqId;

    /**
     * 错误描述
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private String errContent;

    /**
     * 错误简述
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private String errDec;

    /**
     * 用户编号
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private Long createdBy;

    /**
     * 创建时间时间
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_sign_err
     *
     * @mbg.generated Tue Feb 02 15:47:52 CST 2021
     */
    private static final long serialVersionUID = 1L;
}
